package uristqwerty.gui_craftguide;

public class Rect
{
	public final int x, y, width, height;

	public Rect(int x, int y, int width, int height)
	{
		this.x = x;
		this.y = y;
		this.width = width;
		this.height = height;
	}

	@Override
	public boolean equals(Object obj)
	{
		if(!(obj instanceof Rect))
			return false;

		Rect other = (Rect)obj;
		return this.x == other.x && this.width == other.width &&
				this.y == other.y && this.height == other.height;
	}


	// Generated by eclipse. Considering spatial nature, a larger prime may be preferable.
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + height;
		result = prime * result + width;
		result = prime * result + x;
		result = prime * result + y;
		return result;
	}
}
